### ISSUE TITLE
AdminJS v7 - feedback, urgent issues, questions, discussions

### ISSUE THREAD

**Issue by dziraf** [SoftwareBrothers/adminjs#1473]
This is a thread to aggregate all questions/feedback/urgent bugs/discussions related to the recently released version 7.

Feel free to share your ideas or let us know about any issues you're facing related to migration or usage.

**[What's new in version 7
](https://docs.adminjs.co/installation/whats-new-in-v7)**

**[Migration Guide](https://docs.adminjs.co/installation/migration-guide-v7)**

If you notice that parts of our documentation are outdated or unclear, please share that in this thread as well.

**Comment by ddresch** [comment]
Working on a migration of a super basic app with just 4-5 resources and mongoose schema setup. Did the pnpm / npm / yarn update and now the system can't find the packages anymore. 

https://www.npmjs.com/package/@adminjs/mongoose the docs are wrong - still showing require statements.

```js
import { Database as MongooseDatabase, Resource as MongooseResource } from '@adminjs/mongoose';
```

Using this like in the new example app is dropping the error I'm mentioning above.

**Comment by mszula** [comment]
Great work guys!

I'm really in favor of moving to ESM-only but I feel like one thing hasn't been thought through. It's cooperation with NestJS which still uses CJS and has no plans to move to ESM.

https://github.com/nestjs/nest/issues/7021

Do you have any solution for that?

**Comment by dziraf** [comment]
@mszula until Nest.js moves to ESM or starts dual packaging, you will either have to set up AdminJS express/fastify way:

**src/app.module.ts**
```typescript
import { Module } from '@nestjs/common';

import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [
    import('@adminjs/nestjs').then(({ AdminModule }) =>
      AdminModule.createAdminAsync({
        useFactory: () => ({
          adminJsOptions: { rootPath: '/' },
        }),
      }),
    ),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    // ...
    "moduleResolution": "nodenext"
  }
}
```

Instead of `import(...).then(...)` in `app.module.ts` you can just set it up Express way in **main.ts**:
```typescript
import { NestFactory, HttpAdapterHost } from '@nestjs/core';

import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const AdminJS = await import('adminjs');
  const AdminJSExpress = await import('@adminjs/express');

  const expressApp = app.get(HttpAdapterHost).httpAdapter;
  const admin = new AdminJS.default({});

  expressApp.use(
    admin.options.rootPath,
    AdminJSExpress.default.buildRouter(admin),
  );

  await app.listen(3000);
}
bootstrap();
```

Note that these changes still rely on you not actually updating to ESM, so you will have to `await import(<any adminjs package>)` to have it work or just import CJS versions.

As for whether it is possible to still set it up Nest-way - maybe, I don't know. It should be in the interest of NestJS maintainers to proceed with that migration because we cannot impede our own product's development based on their choice of not supporting ESM. Technically ESM projects should be able to import CJS packages, but it doesn't seem to be the case here.

**Comment by dziraf** [comment]
@ddresch Have you managed to fix your problem? From what I can see you just need to make changes to your `tsconfig.json`:

```
"moduleResolution": "nodenext",
"module": "nodenext",
"target": "esnext"
```

**Comment by ddresch** [comment]
Yes – I fixed all my issues now. Thanks for your feedback!

**Comment by Aladinndevolpment** [comment]
TypeError: Unknown file extension ".json"

**Comment by dziraf** [comment]
> TypeError: Unknown file extension ".json"

```
import someJson from './path/to/some.json' assert { type: 'json' }
```

or use alternatives: https://www.stefanjudis.com/snippets/how-to-import-json-files-in-es-modules-node-js/

**Comment by dziraf** [comment]
Can you show full error log? This could be Nest issue since json imports work fine with every other framework I tried.

**Comment by Aladinndevolpment** [comment]
TypeError: Unknown file extension ".json" for E:\application\admin-mode\node_modules\adminjs\lib\locale\de\translation.json

**Comment by dziraf** [comment]
@Aladinndevolpment Looks like type assertions are supported from Node 17+

**Comment by mickyarun** [comment]
I am stuck with this issue after upgrading to 7 both themes and typeorm is not detecting though in node_modules it exist
![image](https://user-images.githubusercontent.com/6388860/233291757-ed3f78f5-051b-463d-abf5-e3006fa32a8d.png)

**Comment by dziraf** [comment]
@mickyarun This is the same problem @ddresch had, I think you just have to add:
```
"moduleResolution": "nodenext",
"module": "nodenext",
"target": "esnext"
```
to your `tsconfig.json`

**Comment by aeroldb** [comment]
@dziraf 
is this how I will register the adapter for TypeORM on nestJS?
![image](https://user-images.githubusercontent.com/14822649/233821020-27d72dd4-5adf-4399-9e7c-57404a2a797c.png)

**Comment by sumersm7** [comment]
[BUG] iam new to Adminjs idk if this is worth reporting
iam using mongoose when i edit field with population this happend on dark theme its not visible

light theme
![image](https://user-images.githubusercontent.com/82924076/233832319-b10d695f-3496-4d77-b37d-b9458563f91e.png)

dark theme
![image](https://user-images.githubusercontent.com/82924076/233832328-47398a51-cefe-46d2-ad96-8c780bb8dc7b.png)

**Comment by aeroldb** [comment]
How do I make a resource the parent instead of the database name on the sidebar?

**Comment by dziraf** [comment]
> [BUG] iam new to Adminjs idk if this is worth reporting iam using mongoose when i edit field with population this happend on dark theme its not visible
> 
> light theme ![image](https://user-images.githubusercontent.com/82924076/233832319-b10d695f-3496-4d77-b37d-b9458563f91e.png)
> 
> dark theme ![image](https://user-images.githubusercontent.com/82924076/233832328-47398a51-cefe-46d2-ad96-8c780bb8dc7b.png)

Yes, this is a bug. Thank you for reporting, I passed it up.

> @dziraf is this how I will register the adapter for TypeORM on nestJS? ![image](https://user-images.githubusercontent.com/14822649/233821020-27d72dd4-5adf-4399-9e7c-57404a2a797c.png)

The `registerAdapter` fragment should be somewhere else, even outside of `bootstrap` function.

**Comment by mszula** [comment]
After migration to v7, I always get an error "You have to implement action component for your Action" for custom resource action without component. Something was changed with that, or that's just a bug 😄 ?

`test: {
        actionType: 'resource',
        component: false,
        handler: async () => {
          return {
            notice: {
              message: 'Zamówienia zostały pobrane.',
              type: 'success',
            },
          };
        },
      },`

**Comment by mickyarun** [comment]
> After migration, I am not able to implement any custom page, keep getting no routes matched <img alt="image" width="518" src="https://user-images.githubusercontent.com/6388860/234338670-a2d9b334-5432-4775-b3af-4efcfaf9183c.png"> <img alt="image" width="943" src="https://user-images.githubusercontent.com/6388860/234338875-48ebd589-80f3-4e28-bc64-8a81bf6de6fe.png">
> 
> Implemented same like demo application

Solve it by deleting .adminjs folder it was having old cached code

**Comment by mickyarun** [comment]
I am creating a bundle in CI/CD pipeline after upgrading to 7, I am getting the following error for the image , any help?
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/6388860/234775889-6ef84ac8-ffbf-4373-b4f9-7ed713db5f6b.png">

**Comment by ddresch** [comment]
@mickyarun you need to add the componentLoader instance to the options object of the upload feature instance. Like stated in the error.

**Comment by mickyarun** [comment]
@ddresch I have added in already
import {componentLoader} from "../../../admin/components.js";
`    uploadFeature({
      componentLoader,
      provider: {aws: {region: AWS_REGION, bucket: MERCHANT_OFFER_S3_BUCKET_NAME}},
      validation: {mimeTypes: ["image/png", "image/jpg", "image/jpeg", "image/svg+xml", "image/webp"]},
      uploadPath: (record, filename) => `integrations/${record.id()}/${filename}`,
      properties: {
        file: "integrationFile",
        key: "integrationImage",
        filePath: "integrationFilePath",
        bucket: MERCHANT_OFFER_S3_BUCKET_NAME
      }
    })`

My component file
`import {ComponentLoader} from "adminjs";
import path from "path";
import * as url from "url";

const __dirname = url.fileURLToPath(new URL(".", import.meta.url));
export const componentLoader = new ComponentLoader();

export const add = (url: string, componentName: string): string => componentLoader.add(componentName, path.join(__dirname, url));

export const CashbackQRCode = add("components/cashbackqrcode", "CashbackQRCode");`

**Comment by mickyarun** [comment]
@dziraf Any help on the above issue, its happening only in production with ADMIN_JS_SKIP_BUNDLE

**Comment by dziraf** [comment]
@mickyarun  If you use `@adminjs/bundler`, did you set `assetsCDN` in `AdminJS` object?

@SOULPWRD is an entry file generated in `.adminjs` folder when you start the server?

**Comment by damian-balas** [comment]
@dziraf 

I hope this message finds you well. I am writing to inquire about the progress on resolving the issue detailed in https://github.com/SoftwareBrothers/adminjs/issues/1347

While I understand that this bug may be deemed less significant, and potentially tedious to address, I was hoping that you could kindly provide me with an estimated timeframe for a resolution.

As a temporary workaround, we can [turn Chrome's autocomplete feature off](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion). However, it would be highly appreciated if an option to address this issue could be implemented as soon as possible.

If it is not possible for you to address this issue within a reasonable timeframe, please let me know if you would welcome a Pull Request from me to resolve the issue.

Thank you for your time and efforts on this matter.

**Comment by ariansobczak-rst** [comment]
> [BUG] iam new to Adminjs idk if this is worth reporting iam using mongoose when i edit field with population this happend on dark theme its not visible
> 
> light theme ![image](https://user-images.githubusercontent.com/82924076/233832319-b10d695f-3496-4d77-b37d-b9458563f91e.png)
> 
> dark theme ![image](https://user-images.githubusercontent.com/82924076/233832328-47398a51-cefe-46d2-ad96-8c780bb8dc7b.png)

Fixed in https://github.com/SoftwareBrothers/adminjs/pull/1495

**Comment by dmitryLagoda** [comment]
Login Page stopped to show errors, e.g in case of incorrect credentials. 
You can try to use wrong credentials in the demo app, it's reproducing.
https://demo.adminjs.co/admin/login

**Comment by sumersm7** [comment]
[BUG] idk if iam doing something wrong or if its specfic to version 7 or not

i am using mongooes adapter

i have a field name idAuthor Refrence to "user" collection 

but when i name it idAuthor it doenst show me dropdown
and when i rename it to author it show dropdown

![image](https://github.com/SoftwareBrothers/adminjs/assets/82924076/de651735-1f82-44bc-86ad-aa024bc26a44)
![image](https://github.com/SoftwareBrothers/adminjs/assets/82924076/006b76ad-25d9-4de7-b636-ac48a8755b52)

is there a way i can keep idAuthor with dropdown

**Comment by mickyarun** [comment]
> assetsCDN

No I didn't added, all generated files are in .adminjs folder

**Comment by ankitr-nalkv** [comment]
[BUG] custom actions with component: false, still show a error page to implement component

Have taken the latest v7.0.6
<img width="826" alt="image" src="https://github.com/SoftwareBrothers/adminjs/assets/14043700/b4237078-de0b-49a3-9f22-2469a4ac0fb3">

The handler associated with the action is called but this page also pops up

**Comment by AstaDK** [comment]
Hi guys. I used Adminjs to build CMS for the express ts app and faced some issues. Could your guys help me to resolve them?
**Issue 1:**
I faced an issue with import libs. For example, I used `@adminks/themes`
```ts 
import { dark, light, noSidebar } from '@adminjs/themes'
```
and I faced issues: Cannot find module `@adminjs/themes` or its corresponding type declarations.ts(2307)
Even though I installed it and it exists in the node_modules. also the same issue with `@adminjs/design-system`

**Issue 2:**
After I set up as an example in a document here: https://docs.adminjs.co/installation/plugins/express#simple
I faced an issue on the browser after the server returned admin page:
> Uncaught Error: ThemeProvider: "theme" prop is required.
    at D (hoist-non-react-statics.cjs.js:103:38)
    at hoist-non-react-statics.cjs.js:103:38
    at hoist-non-react-statics.cjs.js:103:38
    at mountMemo (global.bundle.js:21484:20)
    at Object.useMemo (global.bundle.js:21929:17)
    at Object.useMemo (global.bundle.js:1682:23)
    at Le (hoist-non-react-statics.cjs.js:103:38)
    at renderWithHooks (global.bundle.js:20564:19)
    at mountIndeterminateComponent (global.bundle.js:24328:14)
    at beginWork (global.bundle.js:25841:17) 
    
Hope for any suggestions from your guys.
Node: 18
> "@AdminJS/express": "^6.0.0",
"@AdminJS/themes": "^1.0.0",
"adminjs": "^7.0.6""
"@AdminJS/design-system": "^4.0.2",

and tsconfig
```json 
{
  "compilerOptions": {
    "strict": true,
    "jsx": "react",
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "declaration": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": true,
    "target": "ESNext",
    "sourceMap": false,
    "outDir": "./dist",
    "baseUrl": ".",
    "incremental": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "include": ["./src", "src/index.ts", "./public"],
  "exclude": ["./dist", "node_modules"]
}
```

**Comment by radekdp** [comment]
Hi, 
something is wrong with the nested translations

`i18next::translator: missingKey pl translation properties.isActive.true Yes`

I have this key in my translations:
![image](https://github.com/SoftwareBrothers/adminjs/assets/15743323/e6df4217-1a3a-4106-895c-63b33c52ff05)

**Comment by radekdp** [comment]
Hi,
something is wrong with the nested translations

`i18next::translator: missingKey pl translation properties.isActive.true Yes`

I have this key in my translations:
![image](https://github.com/SoftwareBrothers/adminjs/assets/15743323/23397670-0620-4d8f-8f11-dcaa5a805978)

The column header in the table translates correctly, but the translation in the records is missing:
![image](https://github.com/SoftwareBrothers/adminjs/assets/15743323/52502f09-d96b-4eba-9f08-20222e4718d4)

**Comment by ismoilh** [comment]
Hi I am facing issue with importing @adminjs/nestjs and @adminjs/objection packages I am getting error Cannot find module '@adminjs/objection' or its corresponding type declarations. and yes ive tried to put "moduleResolution": "nodenext",
"module": "nodenext",
"target": "esnext" in tsconfig and pacakges are in node_modules folder someone help me I am not doing anything else Ive just written import its throwing issue thats why no screenshots are passed

**Comment by radekdp** [comment]
Hi,
how can I translate in sidebar navigation.name with avaliable translates in system

![image](https://github.com/SoftwareBrothers/adminjs/assets/15743323/623c8b48-4267-4e38-af73-717dbb6f663d)

**Comment by niyrme** [comment]
> Hi,
> something is wrong with the nested translations
> 
> `i18next::translator: missingKey pl translation properties.isActive.true Yes`
> 
> I have this key in my translations:
> ![image](https://github.com/SoftwareBrothers/adminjs/assets/15743323/23397670-0620-4d8f-8f11-dcaa5a805978)
> 
> The column header in the table translates correctly, but the translation in the records is missing:
> ![image](https://github.com/SoftwareBrothers/adminjs/assets/15743323/52502f09-d96b-4eba-9f08-20222e4718d4)
> 
> 
> 
> 

Having either the property translation **or** the nested properties (like `*.true`/`*.false`) works fine. It only breaks once you have both, and always seems to pick the resource ove the nested ones.

**Comment by radekdp** [comment]
> > Hi,
> > something is wrong with the nested translations
> > `i18next::translator: missingKey pl translation properties.isActive.true Yes`
> > I have this key in my translations:
> > ![image](https://user-images.githubusercontent.com/15743323/249770753-23397670-0620-4d8f-8f11-dcaa5a805978.png)
> > The column header in the table translates correctly, but the translation in the records is missing:
> > ![image](https://user-images.githubusercontent.com/15743323/249770904-52502f09-d96b-4eba-9f08-20222e4718d4.png)
> 
> Having either the property translation **or** the nested properties (like `*.true`/`*.false`) works fine. It only breaks once you have both, and always seems to pick the resource ove the nested ones.

That's right, in an earlier version of AdminJs (6.*) this worked fine

**Comment by smiziara** [comment]
> > > Hi,
> > > something is wrong with the nested translations
> > > `i18next::translator: missingKey pl translation properties.isActive.true Yes`
> > > I have this key in my translations:
> > > ![image](https://user-images.githubusercontent.com/15743323/249770753-23397670-0620-4d8f-8f11-dcaa5a805978.png)
> > > The column header in the table translates correctly, but the translation in the records is missing:
> > > ![image](https://user-images.githubusercontent.com/15743323/249770904-52502f09-d96b-4eba-9f08-20222e4718d4.png)
> > 
> > 
> > Having either the property translation **or** the nested properties (like `*.true`/`*.false`) works fine. It only breaks once you have both, and always seems to pick the resource ove the nested ones.
> 
> That's right, in an earlier version of AdminJs (6.*) this worked fine

Seems to be because V06 just got the admin.locales and initialized the redux but V07 does a flatten+unflatten on the locales, so this *.true, *.false etc is now broken.

**Comment by juanmav** [comment]
Hi, I wanted to add AdminJs to my expressjs and typescript project using  "adminjs": "^7.2.0" with "@adminjs/express": "^6.0.0", "@adminjs/sequelize": "^4.0.0",

and getting the error `Cannot find module '@adminjs/sequelize' or its corresponding type declarations.`

My index.ts 

```typescript
import express from 'express';
import AdminJs from 'adminjs';
import AdminJsExpress from '@adminjs/express';
import AdminJsSequelize from '@adminjs/sequelize';
import * as allModels from './models';

const host = process.env.HOST ?? 'localhost';
const port = process.env.PORT ? Number(process.env.PORT) : 3000;
const app = express();

AdminJs.registerAdapter({
  Resource: AdminJsSequelize.Resource,
  Database: AdminJsSequelize.Database,
});

const localModel = Object.values(allModels);
localModel.pop(); // Remove Sequelize instance
localModel.pop(); // Remove Sequelize instance

const adminOptions =
  {
    // We pass Category to `resources`
    resources: localModel,
  }

const admin = new AdminJs(adminOptions)
const adminRouter = AdminJsExpress.buildRouter(admin)

app.use(admin.options.rootPath, adminRouter);

app.get('/', (req, res) => {
  res.send({ message: 'Hello API' });
});

app.listen(port, host, () => {
  console.log(`[ ready ] http://${host}:${port}`);
});
```

My tsconfig.base.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2020", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {}
  },
  "exclude": ["node_modules", "tmp"]
}

```

Besides that I tried to use AdminJs version 6 but when NPM tries to resolve the version of @adminjs/express and @admin/sequelize it can not resolve the versions of the dependencies in a straigthforward way.

Any advice how is the best way to proceed? 

Thanks in advance
Juan Manuel

**Comment by niyrme** [comment]
> Hi, I wanted to add AdminJs to my expressjs and typescript project using  "adminjs": "^7.2.0" with "@adminjs/express": "^6.0.0", "@adminjs/sequelize": "^4.0.0",
> 
> and getting the error `Cannot find module '@adminjs/sequelize' or its corresponding type declarations.`
> 
> My index.ts 
> 
> ```typescript
> import express from 'express';
> import AdminJs from 'adminjs';
> import AdminJsExpress from '@adminjs/express';
> import AdminJsSequelize from '@adminjs/sequelize';
> import * as allModels from './models';
> 
> const host = process.env.HOST ?? 'localhost';
> const port = process.env.PORT ? Number(process.env.PORT) : 3000;
> const app = express();
> 
> AdminJs.registerAdapter({
>   Resource: AdminJsSequelize.Resource,
>   Database: AdminJsSequelize.Database,
> });
> 
> const localModel = Object.values(allModels);
> localModel.pop(); // Remove Sequelize instance
> localModel.pop(); // Remove Sequelize instance
> 
> const adminOptions =
>   {
>     // We pass Category to `resources`
>     resources: localModel,
>   }
> 
> const admin = new AdminJs(adminOptions)
> const adminRouter = AdminJsExpress.buildRouter(admin)
> 
> app.use(admin.options.rootPath, adminRouter);
> 
> app.get('/', (req, res) => {
>   res.send({ message: 'Hello API' });
> });
> 
> app.listen(port, host, () => {
>   console.log(`[ ready ] http://${host}:${port}`);
> });
> ```
> 
> My tsconfig.base.json
> ```json
> {
>   "compileOnSave": false,
>   "compilerOptions": {
>     "rootDir": ".",
>     "sourceMap": true,
>     "declaration": false,
>     "moduleResolution": "node",
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "importHelpers": true,
>     "target": "es2015",
>     "module": "esnext",
>     "lib": ["es2020", "dom"],
>     "skipLibCheck": true,
>     "skipDefaultLibCheck": true,
>     "baseUrl": ".",
>     "paths": {}
>   },
>   "exclude": ["node_modules", "tmp"]
> }
> 
> ```
> 
> Besides that I tried to use AdminJs version 6 but when NPM tries to resolve the version of @adminjs/express and @admin/sequelize it can not resolve the versions of the dependencies in a straigthforward way.
> 
> Any advice how is the best way to proceed? 
> 
> Thanks in advance
> Juan Manuel

I had that issue as well first, but setting `module` and `moduleResolution` to `"NodeNext"` in the `tsconfig.json` seems to resolve that issue

**Comment by rlamorea** [comment]
Like @Aladinndevolpment I'm in a catch-22 with the JSON import.

Using express with javascript.

Using nodejs 17.3 I get this when I try to start app.js (this is the app.js from the getting started documentation)
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /Users/rick/projects/rasi/taxservice/node_modules/adminjs/lib/locale/de/translation.json
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:22:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v17.3.0
```

If I try to go back to an earlier nodejs (e.g. 16.13) it fails on the `assert` (which requires 17+).

I'm two pages into the getting started tutorial and completely blocked.

**Comment by lpbonomi** [comment]
Calls to create certain models get stuck (the network request status is 'pending' forever) always, they don't even access the before hooks, any idea why?

**Comment by qtnx** [comment]
For those integrating AdminJS with a NestJS monorepo, follow the steps below to configure it properly.

1. Modify the tsconfig.app.json File:

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "moduleResolution": "nodenext",
    "module": "nodenext",
    "target": "esnext",
    "declaration": false,
    "outDir": "../../dist/apps/admin"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist", "test", "**/*spec.ts"]
}
```

2. Disable `webpack` option in `nest-cli.json`

Set `webpack` to `false` inside `compilerOptions`
Example, my sub-app named `admin`
```
"admin": {
      "type": "application",
      "root": "apps/admin",
      "entryFile": "main",
      "sourceRoot": "apps/admin/src",
      "compilerOptions": {
        "webpack": false,
        "tsConfigPath": "apps/admin/tsconfig.app.json"
      }
    }
```

**Comment by SOULPWRD** [comment]
> @mickyarun If you use `@adminjs/bundler`, did you set `assetsCDN` in `AdminJS` object?
> 
> @SOULPWRD is an entry file generated in `.adminjs` folder when you start the server?

Hi, yes it is. 

```AdminJS.UserComponents = {}
import Component0 from '../node_modules/@adminjs/passwords/components/edit'
AdminJS.UserComponents.Component0 = Component0
import JsonbFieldShow from '../src/JsonbShow'
AdminJS.UserComponents.JsonbFieldShow = JsonbFieldShow
import JsonbFieldEdit from '../src/JsonbEdit'
AdminJS.UserComponents.JsonbFieldEdit = JsonbFieldEdit
```
Sorry for a late reply. I was waiting until the version 7 gets a bit stable. Unfortunately, the problem still persists.

**Comment by varshiludani** [comment]
Hi @dziraf, I'm facing issues with deleting rows with Hapi and TypeORM. Just created a new project and tried again.

**Comment by wtime** [comment]
> > > > Hi,
> > > > something is wrong with the nested translations
> > > > `i18next::translator: missingKey pl translation properties.isActive.true Yes`
> > > > I have this key in my translations:
> > > > ![image](https://user-images.githubusercontent.com/15743323/249770753-23397670-0620-4d8f-8f11-dcaa5a805978.png)
> > > > The column header in the table translates correctly, but the translation in the records is missing:
> > > > ![image](https://user-images.githubusercontent.com/15743323/249770904-52502f09-d96b-4eba-9f08-20222e4718d4.png)
> > > 
> > > 
> > > Having either the property translation **or** the nested properties (like `*.true`/`*.false`) works fine. It only breaks once you have both, and always seems to pick the resource ove the nested ones.
> > 
> > 
> > That's right, in an earlier version of AdminJs (6.*) this worked fine
> 
> Seems to be because V06 just got the admin.locales and initialized the redux but V07 does a flatten+unflatten on the locales, so this *.true, *.false etc is now broken.

Hey @dziraf do you have in mind when you will be able to fix this issue?

**Comment by hieupham1203** [comment]
Hi, I see adminjs/mongoose is using MongooseModel.count, but this function is deprecated. I got error. Please check and update.

![Uploading image.png…]()

<img width="849" alt="image" src="https://github.com/SoftwareBrothers/adminjs/assets/133733077/8c181169-8396-473f-9124-e259fa65ca09">
<img width="1019" alt="image" src="https://github.com/SoftwareBrothers/adminjs/assets/133733077/4f99f52d-d65a-46fd-9a70-5a9c29a9a560">

**Comment by rushg171** [comment]
Same here! MongooseModel.count() is deprecated! Will it be fixed in the next version?

**Comment by jakapurg** [comment]
Hey guys, a minor issue I found while adding filters on page navigation.

The following to options act differently.
options: {
                    href: () => undefined,
                    href: undefined
}

The first  one hides the resource from the navigation, but it is still acccessible via URL, while the second correctly shows the resource in navigation.

**Comment by Monyster** [comment]
Need help please.

I want to create a mono repo with 3 folders:
- adminjs
- api
- shared

Adminjs, created with _adminjs create_ (v7 on nest.js). As written in documents, it only supports ESM. 
The api is a simple nest application with mongoose. As I understand it, it only supports CJS. 
A shared folder is a folder that contains some nestjs/mongoose utilities and schemas with decorators.

Maybe someone has faced a similar problem. How to describe package.json and tsconfig to connect a shared folder to each application together. Maybe someone can describe an example please. Or maybe someone sees some available repositories to look at?

I have already tried to make shared folders for build/esm/... and build/cjs/... But it doesn't help and I have problems after building the main applications. Each time there are different import issues and I can't solve them.

I am grateful to everyone who responds.

**Comment by prsws** [comment]
Cannot override Login page in v7. Tried adding componentLoader.override() in various files (app, config options, index) to no avail. Any suggestions? Thanks

**Comment by prsws** [comment]
Is there a simple way to use buildAuthenticatedRouter (express) using 'username' instead of 'email' as the required parameter? I noticed it's coded in types.ts but it's difficult to replace 'authenticate' (AuthenticationOptions) in practice (app.ts). The reason is that in my application a person can reuse its email address (e.g. as staff with multiple roles, as a tenant with multiple shops, or a customer doing business with different tenants) but is always constrained to a distinct username for each instance. So far AdminJS is great, thanks!

**Comment by bmbaron** [comment]
> [@Aladinndevolpment](https://github.com/Aladinndevolpment) Looks like type assertions are supported from Node 17+

I'm having this problem with Node version 23.4.0
